## To Run:

In a folder named "Data" place the following csv files:
- Grab file train.csv from NFL Big Data Bowl 2020 and name as "NFL2020.csv" 
- Grab file plays.csv from NFL Big Data Bowl 2021 and name as "NFL2021Plays.csv" 
- Grab file plays.csv from NFL Big Data Bowl 2022 and name as "NFL2022Plays.csv"

In [1]:
import pandas as pd

# Setting up Run Dataframe

In [4]:
df_2020 = pd.read_csv('Data/NFL2020.csv')

df_runs = df_2020[["GameId", "PlayId", "YardLine", "Quarter", "GameClock", "PossessionTeam", "Down", "Distance", "FieldPosition", "HomeScoreBeforePlay", "VisitorScoreBeforePlay", "HomeTeamAbbr", "VisitorTeamAbbr"]]

print(df_runs)

/var/folders/gj/kqxll8h94db0lnysf3tzxk5r0000gn/T/ipykernel_6493/1936174412.py:1: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv('Data/NFL2020.csv')

            GameId          PlayId  YardLine  Quarter GameClock  \
0       2017090700  20170907000118        35        1  14:14:00
1       2017090700  20170907000118        35        1  14:14:00
2       2017090700  20170907000118        35        1  14:14:00
3       2017090700  20170907000118        35        1  14:14:00
4       2017090700  20170907000118        35        1  14:14:00
...            ...             ...       ...      ...       ...
682149  2019112500  20191125003789        38        4  04:11:00
682150  2019112500  20191125003789        38        4  04:11:00
682151  2019112500  20191125003789        38        4  04:11:00
682152  2019112500  20191125003789        38        4  04:11:00
682153  2019112500  20191125003789        38        4  04:11:00

       PossessionTeam  Down  Distance FieldPosition  HomeScoreBeforePlay  \
0                  NE     3         2            NE                    0
1                  NE     3         2            NE                    0
2                  NE     3         2            NE                    0
3                  NE     3         2            NE                    0
4                  NE     3         2            NE                    0
...               ...   ...       ...           ...                  ...
682149            BLT     2         9           BLT                    6
682150            BLT     2         9           BLT                    6
682151            BLT     2         9           BLT                    6
682152            BLT     2         9           BLT                    6
682153            BLT     2         9           BLT                    6

        VisitorScoreBeforePlay HomeTeamAbbr VisitorTeamAbbr
0                            0           NE              KC
1                            0           NE              KC
2                            0           NE              KC
3                            0           NE              KC
4                            0           NE              KC
...                        ...          ...             ...
682149                      45           LA             BAL
682150                      45           LA             BAL
682151                      45           LA             BAL
682152                      45           LA             BAL
682153                      45           LA             BAL

[682154 rows x 13 columns]

In [10]:
# Number of Unique Games in df_runs

uniqueGameIds_runs = df_runs.GameId.unique()
uniqueGameIdsCount_runs = len(uniqueGameIds_runs)

print("Number of Unique Games for 2020 dataset: ", uniqueGameIdsCount_runs)

Number of Unique Games for 2020 dataset:  688

In [11]:
# First Game of dataset (GameId = 2017090700)

firstGame = df_runs.loc[df_runs['GameId'] == 2017090700]

print("First Game: \n", firstGame)

First Game:
           GameId          PlayId  YardLine  Quarter GameClock PossessionTeam  \
0     2017090700  20170907000118        35        1  14:14:00             NE
1     2017090700  20170907000118        35        1  14:14:00             NE
2     2017090700  20170907000118        35        1  14:14:00             NE
3     2017090700  20170907000118        35        1  14:14:00             NE
4     2017090700  20170907000118        35        1  14:14:00             NE
...          ...             ...       ...      ...       ...            ...
1139  2017090700  20170907004721        33        4  02:32:00             KC
1140  2017090700  20170907004721        33        4  02:32:00             KC
1141  2017090700  20170907004721        33        4  02:32:00             KC
1142  2017090700  20170907004721        33        4  02:32:00             KC
1143  2017090700  20170907004721        33        4  02:32:00             KC

      Down  Distance FieldPosition  HomeScoreBeforePlay  \
0        3         2            NE                    0
1        3         2            NE                    0
2        3         2            NE                    0
3        3         2            NE                    0
4        3         2            NE                    0
...    ...       ...           ...                  ...
1139     3         1            NE                   27
1140     3         1            NE                   27
1141     3         1            NE                   27
1142     3         1            NE                   27
1143     3         1            NE                   27

      VisitorScoreBeforePlay HomeTeamAbbr VisitorTeamAbbr
0                          0           NE              KC
1                          0           NE              KC
2                          0           NE              KC
3                          0           NE              KC
4                          0           NE              KC
...                      ...          ...             ...
1139                      42           NE              KC
1140                      42           NE              KC
1141                      42           NE              KC
1142                      42           NE              KC
1143                      42           NE              KC

[1144 rows x 13 columns]

In [12]:
# Number of Unique Plays for GameId = 2017090700 in df_runs

uniquePlaysFirstGame = firstGame.PlayId.unique()
uniquePlaysFirstGameCount = len(uniquePlaysFirstGame)

print("Number of Unique Plays for First Game: ", uniquePlaysFirstGameCount)

Number of Unique Plays for First Game:  52

In [13]:
# GameId = 2017090700 with Unqiue Plays in first game of df_runs

firstGameDf = firstGame.drop_duplicates(subset=["PlayId"])
firstGameDf.count()
firstGameDf

,GameId,PlayId,YardLine,Quarter,GameClock,PossessionTeam,Down,Distance,FieldPosition,HomeScoreBeforePlay,VisitorScoreBeforePlay,HomeTeamAbbr,VisitorTeamAbbr
0,2017090700,20170907000118,35,1,14:14:00,NE,3,2,NE,0,0,NE,KC
22,2017090700,20170907000139,43,1,13:52:00,NE,1,10,NE,0,0,NE,KC
44,2017090700,20170907000189,35,1,13:02:00,NE,1,10,KC,0,0,NE,KC
66,2017090700,20170907000345,2,1,12:12:00,NE,2,2,KC,0,0,NE,KC
88,2017090700,20170907000395,25,1,12:08:00,KC,1,10,KC,7,0,NE,KC
110,2017090700,20170907000473,29,1,11:21:00,NE,3,7,KC,7,0,NE,KC
132,2017090700,20170907000516,19,1,10:34:00,NE,2,10,KC,7,0,NE,KC
154,2017090700,20170907000653,10,1,09:34:00,NE,4,1,KC,7,0,NE,KC
176,2017090700,20170907000680,10,1,09:25:00,KC,1,10,KC,7,0,NE,KC
198,2017090700,20170907000801,50,1,06:34:00,KC,1,10,NaN,7,0,NE,KC
220,2017090700,20170907000917,9,1,03:47:00,KC,2,9,NE,7,0,NE,KC
242,2017090700,20170907001004,25,1,03:03:00,NE,1,10,NE,7,7,NE,KC
264,2017090700,20170907001077,30,1,01:36:00,NE,1,10,KC,7,7,NE,KC
286,2017090700,20170907001156,12,1,00:37:00,NE,2,5,KC,7,7,NE,KC
308,2017090700,20170907001177,8,1,00:23:00,NE,3,1,KC,7,7,NE,KC
330,2017090700,20170907001296,45,2,14:44:00,KC,2,10,KC,10,7,NE,KC
352,2017090700,20170907001355,18,2,13:17:00,NE,1,10,NE,10,7,NE,KC
374,2017090700,20170907001376,22,2,12:49:00,NE,2,6,NE,10,7,NE,KC
396,2017090700,20170907001443,48,2,11:23:00,NE,2,10,NE,10,7,NE,KC
418,2017090700,20170907001488,36,2,09:57:00,NE,1,10,KC,10,7,NE,KC
440,2017090700,20170907001509,20,2,09:17:00,NE,1,10,KC,10,7,NE,KC
462,2017090700,20170907001530,11,2,08:38:00,NE,2,1,KC,10,7,NE,KC
484,2017090700,20170907001551,7,2,08:15:00,NE,1,7,KC,10,7,NE,KC
506,2017090700,20170907001605,2,2,07:31:00,NE,1,2,KC,10,7,NE,KC
528,2017090700,20170907001664,23,2,07:22:00,KC,1,10,KC,17,7,NE,KC
550,2017090700,20170907001715,36,2,06:11:00,KC,1,10,KC,17,7,NE,KC
572,2017090700,20170907001736,37,2,05:29:00,KC,2,9,KC,17,7,NE,KC
594,2017090700,20170907001819,40,2,03:44:00,NE,1,10,NE,17,7,NE,KC
616,2017090700,20170907001955,4,2,02:29:00,KC,1,14,KC,17,7,NE,KC
638,2017090700,20170907002430,25,3,15:00:00,KC,1,10,KC,17,14,NE,KC
660,2017090700,20170907002648,28,3,10:53:00,NE,1,10,NE,17,14,NE,KC
682,2017090700,20170907002669,30,3,10:23:00,NE,2,8,NE,17,14,NE,KC
704,2017090700,20170907002829,25,3,09:13:00,NE,2,10,NE,17,21,NE,KC
726,2017090700,20170907002900,46,3,07:55:00,NE,2,10,NE,17,21,NE,KC
748,2017090700,20170907002961,14,3,07:08:00,KC,1,10,KC,17,21,NE,KC
770,2017090700,20170907003138,1,3,05:35:00,NE,1,1,KC,17,21,NE,KC
792,2017090700,20170907003161,1,3,05:03:00,NE,2,1,KC,17,21,NE,KC
814,2017090700,20170907003261,11,3,04:21:00,KC,2,12,KC,24,21,NE,KC
836,2017090700,20170907003444,18,3,02:31:00,NE,1,10,KC,24,21,NE,KC
858,2017090700,20170907003465,11,3,02:00:00,NE,2,3,KC,24,21,NE,KC
880,2017090700,20170907003507,4,3,00:57:00,NE,2,4,KC,24,21,NE,KC
902,2017090700,20170907003635,5,3,00:04:00,KC,1,15,KC,27,21,NE,KC
924,2017090700,20170907003874,40,4,12:29:00,NE,4,1,KC,27,28,NE,KC
946,2017090700,20170907004025,13,4,10:28:00,NE,1,10,NE,27,28,NE,KC
968,2017090700,20170907004046,15,4,10:00:00,NE,2,8,NE,27,28,NE,KC
990,2017090700,20170907004182,49,4,08:20:00,KC,2,1,KC,27,28,NE,KC
1012,2017090700,20170907004314,4,4,05:19:00,KC,1,4,NE,27,28,NE,KC
1034,2017090700,20170907004465,21,4,04:15:00,KC,1,10,KC,27,35,NE,KC
1056,2017090700,20170907004486,21,4,04:05:00,KC,1,10,NE,27,35,NE,KC
1078,2017090700,20170907004622,42,4,02:44:00,KC,1,10,NE,27,42,NE,KC
1100,2017090700,20170907004660,40,4,02:37:00,KC,2,8,NE,27,42,NE,KC
1122,2017090700,20170907004721,33,4,02:32:00,KC,3,1,NE,27,42,NE,KC

In [53]:
# Entire df_runs with unique plays (every game)

df_runs_uniquePlays = df_runs.drop_duplicates(subset=["PlayId"])
print(df_runs_uniquePlays)
print(df_runs_uniquePlays.count())

            GameId          PlayId  Team  YardLine  Quarter GameClock  \
0       2017090700  20170907000118  away        35        1  14:14:00
22      2017090700  20170907000139  away        43        1  13:52:00
44      2017090700  20170907000189  away        35        1  13:02:00
66      2017090700  20170907000345  away         2        1  12:12:00
88      2017090700  20170907000395  away        25        1  12:08:00
...            ...             ...   ...       ...      ...       ...
682044  2019112500  20191125003419  away        46        4  09:47:00
682066  2019112500  20191125003440  away        47        4  09:03:00
682088  2019112500  20191125003496  away        13        4  08:04:00
682110  2019112500  20191125003768  away        37        4  04:55:00
682132  2019112500  20191125003789  away        38        4  04:11:00

       PossessionTeam  Down  Distance FieldPosition  HomeScoreBeforePlay  \
0                  NE     3         2            NE                    0
22                 NE     1        10            NE                    0
44                 NE     1        10            KC                    0
66                 NE     2         2            KC                    0
88                 KC     1        10            KC                    7
...               ...   ...       ...           ...                  ...
682044            BLT     1        10           BLT                    6
682066            BLT     2         9           BLT                    6
682088            BLT     1        10            LA                    6
682110            BLT     1        10           BLT                    6
682132            BLT     2         9           BLT                    6

        VisitorScoreBeforePlay HomeTeamAbbr VisitorTeamAbbr
0                            0           NE              KC
22                           0           NE              KC
44                           0           NE              KC
66                           0           NE              KC
88                           0           NE              KC
...                        ...          ...             ...
682044                      42           LA             BAL
682066                      42           LA             BAL
682088                      42           LA             BAL
682110                      45           LA             BAL
682132                      45           LA             BAL

[31007 rows x 14 columns]
GameId                    31007
PlayId                    31007
Team                      31007
YardLine                  31007
Quarter                   31007
GameClock                 31007
PossessionTeam            31007
Down                      31007
Distance                  31007
FieldPosition             30616
HomeScoreBeforePlay       31007
VisitorScoreBeforePlay    31007
HomeTeamAbbr              31007
VisitorTeamAbbr           31007
dtype: int64

In [54]:
# Field position can be NaN because of the ball at the 50 yard line
# There are a total of 31007 unique run plays within the 2020 NFL Big Data Bowl dataset

# Setting up Passing Dataframe
(Does not have homeTeamAbbr or visitorTeamAbbr. Will need games.csv from 2021.)

In [9]:
df_2021 = pd.read_csv('Data/NFL2021Plays.csv')

df_passes = df_2021[["gameId", "playId", "yardlineNumber", "quarter", "gameClock", "possessionTeam", "down", "yardsToGo", "yardlineSide", "preSnapHomeScore", "preSnapVisitorScore"]]

print(df_passes)

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
0      2018090600      75              20        1  15:00:00            ATL
1      2018090600     146              39        1  13:10:00            ATL
2      2018090600     168              39        1  13:05:00            ATL
3      2018090600     190              39        1  13:01:00            ATL
4      2018090600     256               1        1  10:59:00            ATL
...           ...     ...             ...      ...       ...            ...
19234  2018122200    2300              31        3       NaN            WAS
19235  2018122200    3177              37        4       NaN            TEN
19236  2018122201     566              49        1       NaN            LAC
19237  2018122201    1719              48        2       NaN            LAC
19238  2018122201    2649              49        3       NaN            BAL

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore
0         1         15          ATL               0.0                  0.0
1         1         10          PHI               0.0                  0.0
2         2         10          PHI               0.0                  0.0
3         3         10          PHI               0.0                  0.0
4         3          1          PHI               0.0                  0.0
...     ...        ...          ...               ...                  ...
19234     2          5          WAS               NaN                  NaN
19235     3          7          WAS               NaN                  NaN
19236     3          4          LAC               NaN                  NaN
19237     3          1          LAC               NaN                  NaN
19238     1         10          LAC               NaN                  NaN

[19239 rows x 11 columns]

In [14]:
# Entire df_passes with unique plays (every game)

df_passes_uniquePlays = df_passes.drop_duplicates(subset=["playId"])
print(df_passes_uniquePlays)
print(df_passes_uniquePlays.count())

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
0      2018090600      75              20        1  15:00:00            ATL
1      2018090600     146              39        1  13:10:00            ATL
2      2018090600     168              39        1  13:05:00            ATL
3      2018090600     190              39        1  13:01:00            ATL
4      2018090600     256               1        1  10:59:00            ATL
...           ...     ...             ...      ...       ...            ...
19047  2018120202    4488              25        4       NaN            DET
19111  2018120910    4369               3        4       NaN            DEN
19178  2018122309    5056              40        5       NaN             GB
19188  2018122304     397               3        1       NaN            CAR
19201  2018122313    4658              47        4       NaN            PIT

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore
0         1         15          ATL               0.0                  0.0
1         1         10          PHI               0.0                  0.0
2         2         10          PHI               0.0                  0.0
3         3         10          PHI               0.0                  0.0
4         3          1          PHI               0.0                  0.0
...     ...        ...          ...               ...                  ...
19047     3         10          DET               NaN                  NaN
19111     1          3           SF               NaN                  NaN
19178     3         10           GB               NaN                  NaN
19188     3          3          ATL               NaN                  NaN
19201     2         10           NO               NaN                  NaN

[4592 rows x 11 columns]
gameId                 4592
playId                 4592
yardlineNumber         4592
quarter                4592
gameClock              4572
possessionTeam         4592
down                   4592
yardsToGo              4592
yardlineSide           4528
preSnapHomeScore       4572
preSnapVisitorScore    4572
dtype: int64

In [15]:
## Maybe want to get rid rows that have gameClock, preSnapHomeScore and/or preSnapVisitorScore = NaN

# Setting up Punt Dataframe

In [20]:
df_2022 = pd.read_csv('Data/NFL2022Plays.csv')

df_punts = df_2022[["gameId", "playId", "yardlineNumber", "quarter", "gameClock", "possessionTeam", "down", "yardsToGo", "yardlineSide", "preSnapHomeScore", "preSnapVisitorScore", "specialTeamsPlayType"]]
df_punts = df_punts.loc[df_punts["specialTeamsPlayType"] == "Punt"]

print(df_punts)

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
1      2018090600     366               8        1  09:20:00            PHI
4      2018090600     872              35        1  00:33:00            PHI
5      2018090600     973              11        2  14:18:00            ATL
10     2018090600    1850              31        2  01:30:00            PHI
11     2018090600    1989              26        2  00:44:00            ATL
...           ...     ...             ...      ...       ...            ...
19957  2021010315    1359              20        2  08:17:00             SF
19958  2021010315    1479              23        2  06:47:00            SEA
19964  2021010315    2235              27        3  08:39:00            SEA
19967  2021010315    2497              26        3  05:17:00            SEA
19972  2021010315    3258              41        4  07:52:00             SF

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore  \
1         4          4          PHI                 0                    0
4         4         18          PHI                 0                    3
5         4         19          ATL                 0                    3
10        4          8          PHI                 3                    6
11        4          8          ATL                 3                    6
...     ...        ...          ...               ...                  ...
19957     4         15           SF                 0                    6
19958     4         19          SEA                 0                    6
19964     4          8          SEA                 6                    6
19967     4          9          SEA                 9                    6
19972     4          5           SF                16                   12

      specialTeamsPlayType
1                     Punt
4                     Punt
5                     Punt
10                    Punt
11                    Punt
...                    ...
19957                 Punt
19958                 Punt
19964                 Punt
19967                 Punt
19972                 Punt

[5991 rows x 12 columns]

In [21]:
# Entire df_passes with unique plays (every game)

df_punts_uniquePlays = df_punts.drop_duplicates(subset=["playId"])
print(df_punts_uniquePlays)
print(df_punts_uniquePlays.count())

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
1      2018090600     366               8        1  09:20:00            PHI
4      2018090600     872              35        1  00:33:00            PHI
5      2018090600     973              11        2  14:18:00            ATL
10     2018090600    1850              31        2  01:30:00            PHI
11     2018090600    1989              26        2  00:44:00            ATL
...           ...     ...             ...      ...       ...            ...
19918  2021010313    3282              47        4  08:06:00            JAX
19920  2021010313    3537              15        4  04:36:00            JAX
19944  2021010314    3395              22        4  07:55:00             LA
19946  2021010314    3831              32        4  00:29:00             LA
19948  2021010315     175              33        1  13:07:00            SEA

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore  \
1         4          4          PHI                 0                    0
4         4         18          PHI                 0                    3
5         4         19          ATL                 0                    3
10        4          8          PHI                 3                    6
11        4          8          ATL                 3                    6
...     ...        ...          ...               ...                  ...
19918     4         15          JAX                20                   14
19920     4          6          JAX                20                   14
19944     4          8           LA                18                    7
19946     4          9           LA                18                    7
19948     4         12          SEA                 0                    0

      specialTeamsPlayType
1                     Punt
4                     Punt
5                     Punt
10                    Punt
11                    Punt
...                    ...
19918                 Punt
19920                 Punt
19944                 Punt
19946                 Punt
19948                 Punt

[3198 rows x 12 columns]
gameId                  3198
playId                  3198
yardlineNumber          3198
quarter                 3198
gameClock               3198
possessionTeam          3198
down                    3198
yardsToGo               3198
yardlineSide            3131
preSnapHomeScore        3198
preSnapVisitorScore     3198
specialTeamsPlayType    3198
dtype: int64

# Setting up Field Goal Dataframe

In [22]:
df_field_goals = df_2022[["gameId", "playId", "yardlineNumber", "quarter", "gameClock", "possessionTeam", "down", "yardsToGo", "yardlineSide", "preSnapHomeScore", "preSnapVisitorScore", "specialTeamsPlayType"]]
df_field_goals = df_field_goals.loc[df_field_goals["specialTeamsPlayType"] == "Field Goal"]

print(df_field_goals)

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
2      2018090600     658               3        1  05:03:00            ATL
6      2018090600    1368               8        2  06:12:00            PHI
8      2018090600    1587              34        2  02:13:00            ATL
33     2018090900    1226              23        2  13:18:00            BAL
36     2018090900    1613              34        2  08:48:00            BUF
...           ...     ...             ...      ...       ...            ...
19952  2021010315     811              17        1  02:13:00            SEA
19955  2021010315    1243              12        2  09:31:00            SEA
19959  2021010315    1784              18        2  00:29:00             SF
19962  2021010315    2121              29        3  09:36:00             SF
19965  2021010315    2366              15        3  06:23:00             SF

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore  \
2         4          3          PHI                 0                    0
6         4          8          ATL                 0                    3
8         4         17          PHI                 3                    3
33        4         13          BUF                14                    0
36        4          9          BAL                17                    0
...     ...        ...          ...               ...                  ...
19952     4         10           SF                 0                    0
19955     4          3           SF                 0                    3
19959     4          6          SEA                 0                    6
19962     4          8          SEA                 3                    6
19965     4         15          SEA                 6                    6

      specialTeamsPlayType
2               Field Goal
6               Field Goal
8               Field Goal
33              Field Goal
36              Field Goal
...                    ...
19952           Field Goal
19955           Field Goal
19959           Field Goal
19962           Field Goal
19965           Field Goal

[2657 rows x 12 columns]

In [23]:
# Entire df_passes with unique plays (every game)

df_field_goals_uniquePlays = df_field_goals.drop_duplicates(subset=["playId"])
print(df_field_goals_uniquePlays)
print(df_field_goals_uniquePlays.count())

           gameId  playId  yardlineNumber  quarter gameClock possessionTeam  \
2      2018090600     658               3        1  05:03:00            ATL
6      2018090600    1368               8        2  06:12:00            PHI
8      2018090600    1587              34        2  02:13:00            ATL
33     2018090900    1226              23        2  13:18:00            BAL
36     2018090900    1613              34        2  08:48:00            BUF
...           ...     ...             ...      ...       ...            ...
19905  2021010313    1615               6        2  02:41:00            IND
19928  2021010314    1034              10        2  14:21:00             LA
19938  2021010314    2477              16        3  06:20:00             LA
19962  2021010315    2121              29        3  09:36:00             SF
19965  2021010315    2366              15        3  06:23:00             SF

       down  yardsToGo yardlineSide  preSnapHomeScore  preSnapVisitorScore  \
2         4          3          PHI                 0                    0
6         4          8          ATL                 0                    3
8         4         17          PHI                 3                    3
33        4         13          BUF                14                    0
36        4          9          BAL                17                    0
...     ...        ...          ...               ...                  ...
19905     4          3          JAX                17                    0
19928     4         10          ARI                 0                    7
19938     4         13          ARI                12                    7
19962     4          8          SEA                 3                    6
19965     4         15          SEA                 6                    6

      specialTeamsPlayType
2               Field Goal
6               Field Goal
8               Field Goal
33              Field Goal
36              Field Goal
...                    ...
19905           Field Goal
19928           Field Goal
19938           Field Goal
19962           Field Goal
19965           Field Goal

[1986 rows x 12 columns]
gameId                  1986
playId                  1986
yardlineNumber          1986
quarter                 1986
gameClock               1986
possessionTeam          1986
down                    1986
yardsToGo               1986
yardlineSide            1986
preSnapHomeScore        1986
preSnapVisitorScore     1986
specialTeamsPlayType    1986
dtype: int64